---
title: "과제11"
author: "Joey Choi"
date: '2019 6 27 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(PairedData)
library(dplyr)
library(reshape2)

```
### 2. 다음은 3개 채소에 대한 도매시장 7곳의 가격이다. 3개 채소의 가격이 같다고 할 수 있는가?
[2번 문제 자료](images/4.png)
```{r}
a <- c(15.5, 14.3, 16.3, 13.5, 15.7, 16.4, 14.7)
b <- c(14.7, 16.3, 15.5, 15.2, 16.3, 13.5, 15.4)
c <- c(15.5, 13.2, 16.5, 15.7, 15.3, 15.2, 14.8)
veggies <- data.frame(a,b,c)
veggies <- melt(veggies, variable.name = "Vegetable", value.name = "Price")

ow <- lm(Price~Vegetable, data = veggies)
anova(ow)

# p value = 0.9824 유의수준 0.05 보다 높기 때문에 영가설 기각을 실패함으로써 채소 3개의 가격이 같다고 할 수 있다. 

```
#### Conclusion
p value = 0.9824 유의수준 0.05 보다 높기 때문에 영가설 기각을 실패함으로써 채소 3개의 가격이 같다고 할 수 있다. 

## Question 11. 적합도/독립성 검정
### 1. 어느 공정의 부적합품률은 15% 이다. 시료 80개를 추출하여 검사한 결과 불량이 16개이다. 유의수준 5%로 적합도 검정을 하시오.
```{r}
n <- 80
pTrue <- 0.85
pFalse <- 0.15
alpha <- 0.05
#검정통계량
evTrue <- n * pTrue
evFalse <- n * pFalse
"검정통계량"
t.s <- (((64-evTrue)^2) /evTrue + ((16-evFalse)^2)/evFalse)
"p-value"
1 - pchisq(t.s, df=1)

#fail to reject null hypothesis 
# 유의수준 0.05보다 높기 떄문에 영가설을 기각 15%를 따른 다고 볼수 있다. 
```

#### Conclusion
유의수준 0.05보다 높기 떄문에 영가설을 기각 15%를 따른 다고 볼수 있다. 

### 2. 다음은 음주량과 흡연량 데이터이다. 이 표로부터 음주량과 흡연량 사이에 연관이 있는지 확인하시오.
[2번 문제 자료](images/5.png)

```{r}
#11-2 
s.more <- c(23,31,13)
s.less <- c(21,48,23)
s.none <- c(63,159,119)

smokeDrink <- data.frame(row.names = c("반병 이상", "반병 이하", "못마심"),  s.more, s.less, s.none)
smokeDrink$Sum <- smokeDrink$s.more + smokeDrink$s.less + smokeDrink$s.none 
newRow <- data.frame(row.names = "계", sum(smokeDrink$s.more), sum(smokeDrink$s.less), sum(smokeDrink$s.none))
#newRow

tab <- apply(smokeDrink,c(1,2),sum)
#tab
round(prop.table(tab,margin =2) ,1)
s.n <- margin.table(tab, margin =1)
d.n <- margin.table(tab, margin= 2)

(s.p <- s.n/margin.table(tab))
(d.p <- d.n/margin.table(tab))

(expected <- margin.table(tab) * (s.p %*% t(d.p)))
addmargins(expected)
#chi-squared statistics
o.e <- (tab - expected)^2 / expected
addmargins(o.e)




chisq.t <- sum(o.e) #검정 통계량 
chisq.t
qchisq(chisq.t, df=2) #p value 


chisq.test(tab)
```